# Builder stage
FROM node:22.13.1-alpine3.20 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (including dev dependencies for the build process)
RUN npm install

# Copy the entire application source code
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM node:22.13.1-alpine3.20 AS production

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy the compiled code from the builder stage
COPY --from=builder /app/dist ./dist

# Expose the port the app runs on
EXPOSE 3000

# Set the command to run the application
CMD ["node", "dist/main.js"] #Make sure main.js is your main entry point
