apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcx-cms-api-dev
  labels:
    app: bcx-cms-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcx-cms-api-dev
  template:
    metadata:
      labels:
        app: bcx-cms-api-dev
    spec:
      containers:
      - name: bcx-cms-api-dev
        image: us-central1-docker.pkg.dev/banchanxanh/banchanxanh/bcx-cms-api-dev:latest
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: bcx-cms-api-dev-config
          - secretRef:
              name: bcx-cms-api-dev-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bcx-cms-api-dev-service
  labels:
    app: bcx-cms-api-dev
spec:
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 3000 
  selector:
    app: bcx-cms-api-dev
