name: CI with GCP

on:
  push:
    branches:
      - develop
      - main
env:
  GCP_PROJECT_ID: banchanxanh
  GCP_REGION: us-central1
  DEPLOYMENT_NAME: bcx-cms-api
  GKE_CLUSTER: bcx-cluster
  GKE_REGION: us-central1-a

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Determine Image Tag
      id: image_tag
      run: |
        BRANCH_NAME="${{ github.ref_name }}"
        ENVIRONMENT=""

        if [ "$BRANCH_NAME" == "develop" ]; then
          ENVIRONMENT="dev"
        elif [ "$BRANCH_NAME" == "main" ]; then
          ENVIRONMENT="prod"
        else
          echo "Unsupported branch: $BRANCH_NAME"
          exit 1  # Fail the workflow if the branch is not supported
        fi

        echo "IMAGE_TAG=${{ github.sha }" >> $GITHUB_OUTPUT
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
        echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | cut -d '/' -f 2)" >> $GITHUB_OUTPUT

    - name: Build Docker Image and Push to GCP Artifact Registry
      run: |
        BUILD_IMAGE= ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/banchanxanh/${{ steps.image_tag.outputs.REPOSITORY_NAME }}:${{ steps.image_tag.outputs.IMAGE_TAG }}
        echo "Building image: $BUILD_IMAGE"  # Debugging
        docker buildx create --use
        docker buildx build --push -t BUILD_IMAGE . --file Dockerfile

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}
    
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ steps.image_tag.outputs.REPOSITORY_NAME }}-${{ steps.image_tag.outputs.ENVIRONMENT }} \
        ${{ github.repository }}:${{ steps.image_tag.outputs.IMAGE_TAG }}=BUILD_IMAGE
    - name: Deploy to GKE
      run: kubectl rollout restart deployment/${{ steps.image_tag.outputs.REPOSITORY_NAME }}-${{ steps.image_tag.outputs.ENVIRONMENT }}

    # - name: Wait for Deployment Rollout
    #   run: |
    #     kubectl rollout status deployment/${{ steps.image_tag.outputs.REPOSITORY_NAME }}-${{ steps.image_tag.outputs.IMAGE_TAG }} --timeout=120s
        
